version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=15677743-3bae-4739-9a1d-52c7322a419f
      - POSTGRES_DB=intellect-ink-db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django-backend
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=intellect-ink-db
      - DB_USER=user
      - DB_PASSWORD=15677743-3bae-4739-9a1d-52c7322a419f
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres-data:
    driver: local
