name: Frontend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
# Build Job (with lint)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 21.x
      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend
      - name: Build Project
        run: npm run build
        working-directory: ./frontend
      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./frontend/dist
  # Deploy Job (not used at this point)
  # deploy:
  #   # Add a dependency to the build job
  #   needs: build
  #   # Specify runner + deployment step
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: production-files
  #         path: ./dist
  #     - name: Deploy to GitHub Pages
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.CI_CD_TOKEN }}
  #         publish_dir: ./dist
